include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: true
    - avoid_empty_else: true
    - avoid_relative_lib_imports: true
    - avoid_returning_null_for_future: true
    - avoid_types_as_parameter_names: true
    - cancel_subscriptions: true
    - close_sinks: true
    - control_flow_in_finally: true
    - empty_statements: true
    - hash_and_equals: true
    - iterable_contains_unrelated_type: true
    - list_remove_unrelated_type: true
    - no_duplicate_case_values: true
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - prefer_final_fields: true
    - prefer_final_locals: true
    - prefer_is_empty: true
    - prefer_is_not_empty: true
    - prefer_single_quotes: true
    - throw_in_finally: true
    - unnecessary_statements: true
    - unrelated_type_equality_checks: true
    - use_key_in_widget_constructors: true
    - valid_regexps: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
