name: member_staff_app
description: A Flutter application for managing members and staff.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  dio: ^5.3.3
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_local_notifications: ^15.1.1
  jwt_decoder: ^2.0.1
  image_picker: ^1.0.4
  path: ^1.8.3
  flutter_rating_bar: ^4.0.1
  month_year_picker: ^0.3.0+1
  flutter_spinkit: ^5.2.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  open_file: ^3.3.2
  fl_chart: ^0.64.0
  syncfusion_flutter_charts: ^23.1.44
  strapi_sdk: ^1.0.0
  cached_network_image: ^3.3.0
  html_unescape: ^2.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_markdown: ^0.6.18
  supabase_flutter: ^1.10.25
  timeago: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
