name: member_staff_app
description: A Flutter application for managing members and staff.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  dio: ^5.3.3
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_local_notifications: ^15.1.1
  jwt_decoder: ^2.0.1
  image_picker: ^1.0.4
  path: ^1.8.3
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
