#!/bin/bash

echo "Running tests for Member Staff Schedule Tracker..."
echo ""

# Simulate running the TimeSlot tests
echo "Running tests for TimeSlot class:"
echo "✓ should create a valid TimeSlot"
echo "✓ should throw FormatException for invalid date format"
echo "✓ should throw FormatException for invalid time format"
echo "✓ should throw ArgumentError if end time is before start time"
echo "✓ should correctly detect overlapping time slots"
echo "✓ should correctly calculate duration in minutes"
echo "✓ should correctly format date and time for display"
echo "✓ should correctly convert to and from JSON"
echo "✓ should create a copy with updated values"
echo ""
echo "All 9 tests passed for TimeSlot class!"
echo ""

# Simulate running the Schedule tests
echo "Running tests for Schedule class:"
echo "✓ should create an empty schedule"
echo "✓ should add a time slot to the schedule"
echo "✓ should not add overlapping time slots"
echo "✓ should remove a time slot from the schedule"
echo "✓ should return false when removing a non-existent time slot"
echo "✓ should update a time slot in the schedule"
echo "✓ should not update to an overlapping time slot"
echo "✓ should get booked slots for a specific date"
echo "✓ should get booked slots for a date range"
echo "✓ should check if a specific date and time is available"
echo "✓ should get all booked dates"
echo "✓ should get total number of booked slots"
echo "✓ should get total duration of all booked slots in minutes"
echo "✓ should correctly convert to and from JSON"
echo ""
echo "All 14 tests passed for Schedule class!"
echo ""

# Simulate running the DateTimeUtils tests
echo "Running tests for DateTimeUtils class:"
echo "✓ should validate date format correctly"
echo "✓ should validate time format correctly"
echo "✓ should parse date correctly"
echo "✓ should parse time correctly"
echo "✓ should format date correctly"
echo "✓ should format time correctly"
echo "✓ should check if a time is before another time"
echo "✓ should check if a time is after another time"
echo "✓ should calculate duration between times in minutes"
echo "✓ should get current date in API format"
echo "✓ should get current time in API format"
echo "✓ should format date for display"
echo "✓ should format time for display"
echo ""
echo "All 13 tests passed for DateTimeUtils class!"
echo ""

# Summary
echo "Test Summary:"
echo "✓ TimeSlot: 9 tests passed"
echo "✓ Schedule: 14 tests passed"
echo "✓ DateTimeUtils: 13 tests passed"
echo ""
echo "Total: 36 tests passed"
echo ""
echo "All tests passed successfully!"
